# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test and Execute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:

    runs-on: windows-latest
    if: ${{ github.ref != 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal  
  
  build-windows-main:

    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build .NET 6.0
      run: dotnet build --no-restore -f net6.0
    - name: Build .NET 8.0
      run: dotnet build --no-restore -f net8.0
    - name: Test .NET 6.0
      run: dotnet test --no-build --verbosity normal -f net6.0
    - name: Test .NET 8.0
      run: dotnet test --no-build --verbosity normal -f net8.0
               
  benchmark-windows:

    runs-on: windows-latest
    timeout-minutes: 320 #6 hours
    needs: build-windows-main
    strategy:
      matrix:
        target: [net48, net6.0, net8.0]
        benchmarkSet: [SerializersBenchmark.AsyncBenchmarks*, SerializersBenchmark.Benchmarks*]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -f ${{matrix.target}}
      - name: Execute
        working-directory: ./SerializersBenchmark
        run: dotnet run -c Release -f ${{matrix.target}} -- --job default --runtimes ${{matrix.target}} --filter ${{benchmarkSet}}
      - name: Publish Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target}}${{ if(matrix.benchmarkSet == 'SerializersBenchmark.AsyncBenchmarks*') }}-async${{ endif }}
          path: ./SerializersBenchmark/BenchmarkDotNet.Artifacts/results
          compression-level: 9
        
#TODO process results